name = "LifeFortran"
version = "0.1.0"
license = "license"
author = "Thomas Jones"
maintainer = "tjwalkr3@gmail.com"
copyright = "Copyright 2024, Thomas Jones"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

